"""Initial migration with subtenancy

Revision ID: 7bd8d22de41f
Revises: 
Create Date: 2025-09-19 17:58:58.443606

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision = '7bd8d22de41f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.Enum('WEBHOOK', 'SCHEDULE', name='triggertype'), nullable=False),
    sa.Column('trigger_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_execution_id'), 'executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_executions_function_name'), 'executions', ['function_name'], unique=False)
    op.create_index(op.f('ix_executions_subtenant_id'), 'executions', ['subtenant_id'], unique=False)
    op.create_table('functions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtenant_id', 'name', name='uix_function_subtenant_name')
    )
    op.create_index(op.f('ix_functions_name'), 'functions', ['name'], unique=False)
    op.create_index(op.f('ix_functions_subtenant_id'), 'functions', ['subtenant_id'], unique=False)
    op.create_table('installed_packages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('installed_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtenant_id', 'package_name', name='uix_package_subtenant_name')
    )
    op.create_index(op.f('ix_installed_packages_package_name'), 'installed_packages', ['package_name'], unique=False)
    op.create_index(op.f('ix_installed_packages_subtenant_id'), 'installed_packages', ['subtenant_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtenant_id', 'name', name='uix_schedule_subtenant_name')
    )
    op.create_index(op.f('ix_scheduled_jobs_name'), 'scheduled_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_subtenant_id'), 'scheduled_jobs', ['subtenant_id'], unique=False)
    op.create_table('subtenants',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtenants_subtenant_id'), 'subtenants', ['subtenant_id'], unique=True)
    op.create_table('webhooks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', name='httpmethod'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_values', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtenant_id', 'path', 'http_method', name='uix_webhook_subtenant_path_method')
    )
    op.create_index(op.f('ix_webhooks_path'), 'webhooks', ['path'], unique=False)
    op.create_index(op.f('ix_webhooks_subtenant_id'), 'webhooks', ['subtenant_id'], unique=False)
    op.create_table('function_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('function_id', GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_versions_subtenant_id'), 'function_versions', ['subtenant_id'], unique=False)
    op.create_table('step_executions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subtenant_id', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.execution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_executions_execution_id'), 'step_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_step_executions_subtenant_id'), 'step_executions', ['subtenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_executions_subtenant_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_execution_id'), table_name='step_executions')
    op.drop_table('step_executions')
    op.drop_index(op.f('ix_function_versions_subtenant_id'), table_name='function_versions')
    op.drop_table('function_versions')
    op.drop_index(op.f('ix_webhooks_subtenant_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_path'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_subtenants_subtenant_id'), table_name='subtenants')
    op.drop_table('subtenants')
    op.drop_index(op.f('ix_scheduled_jobs_subtenant_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_name'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_installed_packages_subtenant_id'), table_name='installed_packages')
    op.drop_index(op.f('ix_installed_packages_package_name'), table_name='installed_packages')
    op.drop_table('installed_packages')
    op.drop_index(op.f('ix_functions_subtenant_id'), table_name='functions')
    op.drop_index(op.f('ix_functions_name'), table_name='functions')
    op.drop_table('functions')
    op.drop_index(op.f('ix_executions_subtenant_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_function_name'), table_name='executions')
    op.drop_index(op.f('ix_executions_execution_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###