"""Remove separate subtenant_id column

Revision ID: 8c004ed4e7d7
Revises: 7bd8d22de41f
Create Date: 2025-09-22 15:49:14.541976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c004ed4e7d7'
down_revision = '7bd8d22de41f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('ix_subtenants_subtenant_id'), table_name='subtenants')
    op.drop_column('subtenants', 'subtenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtenants', sa.Column('subtenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_subtenants_subtenant_id'), 'subtenants', ['subtenant_id'], unique=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###