"""fix webhook unique constraint to be global not per subtenant

Revision ID: 8ed80fb195ef
Revises: 8c004ed4e7d7
Create Date: 2025-09-22 18:07:57.539555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ed80fb195ef'
down_revision = '8c004ed4e7d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_constraint('uix_webhook_subtenant_path_method', 'webhooks', type_='unique')
    op.create_unique_constraint('uix_webhook_path_method', 'webhooks', ['path', 'http_method'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_webhook_path_method', 'webhooks', type_='unique')
    op.create_unique_constraint('uix_webhook_subtenant_path_method', 'webhooks', ['subtenant_id', 'path', 'http_method'])
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###