"""add config management fields to skills

Revision ID: 290b7b865281
Revises: 54056f649874
Create Date: 2026-02-01 16:26:11.877753

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "290b7b865281"
down_revision = "54056f649874"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed auto-generated drop of apscheduler_jobs - APScheduler manages its own tables
    op.add_column("skills", sa.Column("managed_by", sa.String(), nullable=True))
    op.add_column("skills", sa.Column("config_name", sa.String(), nullable=True))
    op.add_column("skills", sa.Column("config_checksum", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "config_checksum")
    op.drop_column("skills", "config_name")
    op.drop_column("skills", "managed_by")
    # Note: Removed auto-generated recreation of apscheduler_jobs - APScheduler manages its own tables
    # ### end Alembic commands ###
