"""drop stale ix_table_annotations_table_level index

Revision ID: 6de188a34285
Revises: 08b99e9f39ee
Create Date: 2026-03-10 17:35:46.835215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de188a34285'
down_revision = '08b99e9f39ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_annotations_table_level'), table_name='table_annotations', postgresql_where='(column_name IS NULL)', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_table_annotations_table_level'), 'table_annotations', ['database_connection_id', 'schema_name', 'table_name'], unique=True, postgresql_where='(column_name IS NULL)')
    # ### end Alembic commands ###