"""add collections and files

Revision ID: bf3780240859
Revises: a1c10336abd5
Create Date: 2026-02-12 16:50:00.266343

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision = 'bf3780240859'
down_revision = 'a1c10336abd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('metadata_schema', sa.JSON(), nullable=False),
    sa.Column('content_filter_function', sa.String(length=255), nullable=True),
    sa.Column('post_upload_function', sa.String(length=255), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('max_total_size_gb', sa.Integer(), nullable=False),
    sa.Column('allow_shared_files', sa.Boolean(), nullable=False),
    sa.Column('allow_private_files', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uq_collection_namespace_name')
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_namespace'), 'collections', ['namespace'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('collection_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_collection_id'), 'files', ['collection_id'], unique=False)
    op.create_index('ix_files_collection_visibility', 'files', ['collection_id', 'visibility'], unique=False)
    op.create_index(op.f('ix_files_name'), 'files', ['name'], unique=False)
    op.create_index('ix_files_user_collection', 'files', ['user_id', 'collection_id'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_index(op.f('ix_files_visibility'), 'files', ['visibility'], unique=False)
    op.create_table('content_filter_evaluations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('file_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('function_namespace', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_filter_evaluations_file_id'), 'content_filter_evaluations', ['file_id'], unique=False)
    op.create_index('ix_content_filter_file_version', 'content_filter_evaluations', ['file_id', 'version_number'], unique=False)
    op.create_table('file_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('file_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'version_number', name='uq_file_version'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_index('ix_file_versions_hash', 'file_versions', ['hash_sha256'], unique=False)
    op.create_index(op.f('ix_file_versions_hash_sha256'), 'file_versions', ['hash_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_versions_hash_sha256'), table_name='file_versions')
    op.drop_index('ix_file_versions_hash', table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index('ix_content_filter_file_version', table_name='content_filter_evaluations')
    op.drop_index(op.f('ix_content_filter_evaluations_file_id'), table_name='content_filter_evaluations')
    op.drop_table('content_filter_evaluations')
    op.drop_index(op.f('ix_files_visibility'), table_name='files')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index('ix_files_user_collection', table_name='files')
    op.drop_index(op.f('ix_files_name'), table_name='files')
    op.drop_index('ix_files_collection_visibility', table_name='files')
    op.drop_index(op.f('ix_files_collection_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_namespace'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###