"""add exposed_namespaces to apps

Revision ID: ebe0ac802f33
Revises: f2580dedf6d5
Create Date: 2026-02-21 13:57:29.178879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebe0ac802f33'
down_revision = 'f2580dedf6d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('exposed_namespaces', postgresql.JSON(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'exposed_namespaces')
    # ### end Alembic commands ###