"""add apps table

Revision ID: f2580dedf6d5
Revises: a6b7c8d9e0f1
Create Date: 2026-02-21 13:14:40.106499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2580dedf6d5'
down_revision = 'a6b7c8d9e0f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_resources', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('required_permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('managed_by', sa.String(), nullable=True),
    sa.Column('config_name', sa.String(), nullable=True),
    sa.Column('config_checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uq_app_namespace_name')
    )
    op.create_index(op.f('ix_apps_name'), 'apps', ['name'], unique=False)
    op.create_index(op.f('ix_apps_namespace'), 'apps', ['namespace'], unique=False)
    op.create_index(op.f('ix_apps_user_id'), 'apps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_user_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_namespace'), table_name='apps')
    op.drop_index(op.f('ix_apps_name'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###